[build]
  # Build command
  command = "npm run build"
  
  # Output directory (Vite builds to 'dist')
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Disable Next.js telemetry (not needed for Vite)
  NEXT_TELEMETRY_DISABLED = "1"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"